### ISSUE TITLE
Display of contributions and expenditures for lobbyists don't make a lot of sense 

### ISSUE THREAD

**Issue by fgregg** [datamade/nmid#149]
https://nmid.datamade.us/lobbyists/daniel--najjar-137/

![screenshot-2018-4-10 lobbyist in new mexico](https://user-images.githubusercontent.com/536941/38581553-d2b819f8-3cd2-11e8-8ccd-c35e4def3fc6.png)

The green + contributions and the red negative expenditures suggests that you should add these together to get a sense of how much money the lobbyists has.

That's not really what's going on here. 

I would see if we can use much clearer language, many like

Change contributions to "Cash donations"
Change expenditures to "Gifts"

And have them be the same color.

**Comment by jeancochrane** [comment]
I like the language of "Cash donations" and "Gifts" a lot. Should we change the titles of the tables underneath to match?

**Comment by fgregg** [comment]
Makes sense to me.

**Comment by fgregg** [comment]
I would run that language by the client.

**Comment by fgregg** [comment]
So it looks like you decided to not change the titles of the table underneath?

Also, I would recommend having the tables be in the same order as the summary. I.e. Cash donations first then gifts.

**Comment by jeancochrane** [comment]
I haven't actually gotten confirmation from Marjorie about that -- I'll ping her. Good call on the table order, too.
