### ISSUE TITLE
calculate ordered rank for candidates and committees

### ISSUE THREAD

**Issue by derekeder** [datamade/nmid#5]
let's rank each candidate and committee by the amount of money they have on hand. this should be calculated during the ETL update and stored in the database.

**Comment by fgregg** [comment]
Why should it be done as the ETL? Because it's an expensive query?

**Comment by derekeder** [comment]
@fgregg calculating it on the template side would be expensive. in Illinois Sunshine, we fudge it wit the top 100 and only show it on the home and listing pages.

**Comment by fgregg** [comment]
Thanks for the explanation.
